# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-17 22:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ti_tamba_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videolibrary',
            name='file',
        ),
        migrations.AddField(
            model_name='videolibrary',
            name='files',
            field=models.FileField(null=True, upload_to='videos/'),
        ),
        migrations.AddField(
            model_name='videolibrary',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='videolibrary',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='videolibrary',
            name='uploaded_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
