# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-17 22:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ti_tamba_app', '0002_auto_20180617_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='videolibrary',
            name='age_restriction',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='videolibrary',
            name='genre',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='videolibrary',
            name='year_of_release',
            field=models.DateTimeField(default=2, help_text='Day of the Release', verbose_name='Day of Release'),
            preserve_default=False,
        ),
    ]
