# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-17 22:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ti_tamba_app', '0003_auto_20180617_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='videolibrary',
            name='image_poster',
            field=models.ImageField(null=True, upload_to='posters/'),
        ),
    ]
