# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-01 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ti_tamba_app', '0012_auto_20180628_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actors',
            name='actor_profile',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='videolibrary',
            name='description',
            field=models.TextField(),
        ),
    ]
